### ISSUE TITLE
Buidling fails: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by sedrubal** [nylira/prism-break#1345]
Hi,

Everytime I run the makefile to completely rebuilt the project, I get following error at the end of building. Is this my fail?

```npm
mkdir -p public
cp -r source/dotfiles/.htaccess public
cp -r tmp/* public/
rm -rf tmp

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'tmp/zh-TW/categories/servers/index.html'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at /prism-break/source/functions/write-files.ls:9:15
    at Object.exports.renderFile (/prism-break/node_modules/jade/lib/jade.js:330:12)
    at out$.writeHtml.writeHtml (/prism-break/source/functions/write-files.ls:8:15)
    at write (/prism-break/source/functions/write.ls:150:14)
    at /prism-break/source/functions/write.ls:156:16
    at /prism-break/node_modules/mkdirp/index.js:20:20
    at Object.oncomplete (fs.js:107:15)
make: *** [build_zh-TW] Error 8
make: *** Waiting for unfinished jobs....

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'tmp/zh-CN/protocols/caldav/index.html'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at /prism-break/source/functions/write-files.ls:9:15
    at Object.exports.renderFile (/prism-break/node_modules/jade/lib/jade.js:330:12)
    at out$.writeHtml.writeHtml (/prism-break/source/functions/write-files.ls:8:15)
    at write (/prism-break/source/functions/write.ls:269:14)
    at /prism-break/source/functions/write.ls:275:16
    at /prism-break/node_modules/mkdirp/index.js:20:20
    at Object.oncomplete (fs.js:107:15)
make: *** [build_zh-CN] Error 8

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'tmp/tr/subcategories/os-x-video-voice/index.html'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at /prism-break/source/functions/write-files.ls:9:15
    at Object.exports.renderFile (/prism-break/node_modules/jade/lib/jade.js:330:12)
    at out$.writeHtml.writeHtml (/prism-break/source/functions/write-files.ls:8:15)
    at write (/prism-break/source/functions/write.ls:199:14)
    at /prism-break/source/functions/write.ls:205:16
    at /prism-break/node_modules/mkdirp/index.js:20:20
    at Object.oncomplete (fs.js:107:15)
make: *** [build_tr] Error 8
```

**Comment by vyp** [comment]
`make reset` on master works fine for me:

``` shell
rm -rf public/*
rm -rf tmp/*
mkdir -p tmp/assets/css tmp/assets/js
cp -r source/assets/fonts tmp/assets/fonts
cp -r source/assets/icons tmp/assets/ico
cp -r source/assets/images tmp/assets/img
./node_modules/.bin/stylus -c -u ./node_modules/nib/ <./source/stylesheets/screen.styl >./tmp/assets/css/screen.css
./node_modules/.bin/lsc ./source/functions/build/site-ar.ls
./node_modules/.bin/lsc ./source/functions/build/site-ca.ls
./node_modules/.bin/lsc ./source/functions/build/site-de.ls
./node_modules/.bin/lsc ./source/functions/build/site-el.ls
./node_modules/.bin/lsc ./source/functions/build/site-en.ls
./node_modules/.bin/lsc ./source/functions/build/site-eo.ls
./node_modules/.bin/lsc ./source/functions/build/site-es.ls
./node_modules/.bin/lsc ./source/functions/build/site-fa.ls
./node_modules/.bin/lsc ./source/functions/build/site-fi.ls
./node_modules/.bin/lsc ./source/functions/build/site-fr.ls
./node_modules/.bin/lsc ./source/functions/build/site-he.ls
./node_modules/.bin/lsc ./source/functions/build/site-hi.ls
./node_modules/.bin/lsc ./source/functions/build/site-io.ls
./node_modules/.bin/lsc ./source/functions/build/site-it.ls
./node_modules/.bin/lsc ./source/functions/build/site-ja.ls
./node_modules/.bin/lsc ./source/functions/build/site-nl.ls
./node_modules/.bin/lsc ./source/functions/build/site-no.ls
./node_modules/.bin/lsc ./source/functions/build/site-pl.ls
./node_modules/.bin/lsc ./source/functions/build/site-pt.ls
./node_modules/.bin/lsc ./source/functions/build/site-ru.ls
./node_modules/.bin/lsc ./source/functions/build/site-sr-Cyrl.ls
./node_modules/.bin/lsc ./source/functions/build/site-sr.ls
./node_modules/.bin/lsc ./source/functions/build/site-sv.ls
./node_modules/.bin/lsc ./source/functions/build/site-tr.ls
./node_modules/.bin/lsc ./source/functions/build/site-zh-CN.ls
./node_modules/.bin/lsc ./source/functions/build/site-zh-TW.ls
mkdir -p public
cp -r source/dotfiles/.htaccess public
cp -r tmp/* public/
rm -rf tmp
```

My node is v0.12.7 and npm is 2.13.1, what about yours? And what system are you on?

**Comment by vyp** [comment]
Assuming you have done `npm install` or `npm update` as necessary.

**Comment by strugee** [comment]
From the output it kind of seems like there's a problem somewhere in your installed modules... try `rm -rf node_modules; npm install` and rebuild. After pulling, of course.

**Comment by sedrubal** [comment]
mh this does not work...

```
git pull
git checkout master
make clean
rm -rf node_modules
npm install
make -j4
```

**Comment by vyp** [comment]
What's the error, is it the same? And what's your node version?

**Comment by vyp** [comment]
What about try a new git cloned repository? (Or was that a clean new one?) To do it faster, do `git clone https://github.com/nylira/prism-break --depth 1`. Also, does `make test` work (only building the english version by itself)?

**Comment by sedrubal** [comment]
My node version is `nodejs v0.10.25` (ubuntu build)
I'll try `make test` and so on later...

**Comment by vyp** [comment]
That is probably why. That version is nearly one and a half years old.

**Comment by sedrubal** [comment]
Thanks. Adding `deb https://deb.nodesource.com/node_0.12 trusty main` and updating to `v0.12.7` solved this issue.

**Comment by vyp** [comment]
:smiley: :+1:
